# Generated by Django 3.2.8 on 2021-10-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
