# Generated by Django 3.2.8 on 2021-10-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_person_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
